version: '3'

tasks:
  setup:
    dotenv: ['.env']
    cmds:
      - if [ "$(ls -1 uploads | wc -l)" -gt 0 ]; then rm uploads/*; fi
      - micrate drop
      - micrate create
      - micrate up

  test:
    cmds:
      - crystal spec

  link-uploads:
    cmd: ln -s ./../uploads ./public/uploads

  unlink-uploads:
    cmd: rm ./public/uploads
  dev:
    cmd: shards run api

  test:
    dotenv: ['.env.test']
    cmds:
      - if [ "$(ls -1 uploads | wc -l)" -gt 0 ]; then rm uploads/*; fi
      - micrate drop
      - micrate create
      - micrate up
      - crystal spec --progress --stats

  build:
    cmd: shards build api --release --no-debug --progress --stats --static

  deploy:
    dotenv: ['.env']
    cmds:
      - docker build -t crystal-builder .
      - docker run --rm -v "$PWD/bin:/app/bin" crystal-builder
      - task: unlink-uploads
      - sshpass -p "$DEPLOY_PASSWORD" scp -r ./{bin,db,public,Taskfile.yml} $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_DESTINATION
      - rm -f bin/api
      - task: link-uploads

  build-console:
    cmd: shards build console --release --no-debug --progress --stats --static